version: "3"

services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - sta

  sta:
    build:
      context: .
      dockerfile: Dockerfile
