services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - sta-volume:/app/frontend/dist
    depends_on:
      - sta

  sta:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - sta-volume:/app/frontend/dist
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  mongodb:
    image: mongo:latest
    ports:
      - "4096:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  sta-volume:
  mongodb-data:
